api_platform:
    title: Magazine API
    version: 1.0.0
    enable_swagger: false
    enable_swagger_ui: false
    enable_re_doc: false
    enable_entrypoint: false
    enable_docs: false
    enable_profiler: false

    graphql:
        enabled: true
        default_ide: graphiql
        graphiql:
            enabled: true
        collection:
            pagination:
                enabled: false

    mercure:
        enabled: false
        hub_url: null
    messenger:
        enabled: false

    mapping:
        paths: ['%kernel.project_dir%/src/Entity']

    formats:
        multipart: ['multipart/form-data']
        graphql:   ['application/graphql']
        jsonld:    ['application/ld+json']
        jsonhal:   ['application/hal+json']
        jsonapi:   ['application/vnd.api+json']
        json:      ['application/json']
        xml:       ['application/xml', 'text/xml']
        yaml:      ['application/x-yaml']
        csv:       ['text/csv']
        html:      ['text/html']
