version: '3.8'

volumes:
  m-pgdata:

services:
  blackfire:
    build:
      context: ./.docker/blackfire
      dockerfile: Dockerfile
    ports:
      - "8707:8707"
    container_name: m-blackfire
    env_file:
      - .env.local

  pgsql:
    build:
      context: ./.docker/pgsql
      dockerfile: Dockerfile
    container_name: m-pgsql
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=passwoRt
      - POSTGRES_USER=web
      - POSTGRES_DB=m
    volumes:
      - 'm-pgdata:/var/lib/postgresql/data'
      - '.docker/pgsql/init-schema.sql:/docker-entrypoint-initdb.d/init-schema.sql'
      - '.docker/pgsql/postgresql.conf:/etc/postgresql/postgresql.conf'

  php:
    build:
      context: ./.docker/php
      dockerfile: Dockerfile
    volumes:
      - '.:/var/www/app'
      - '.docker/php/php.ini:/usr/local/etc/php/php.ini'
      - '.docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini'
    container_name: m-php
    ports:
      - "9000:9000" # php-fpm
    depends_on:
      - pgsql
      - blackfire
    expose:
      - "9001" # xdebug

  nginx:
    build:
      context: ./.docker/nginx
      dockerfile: Dockerfile
    volumes:
      - '.:/var/www/app'
      - '.docker/nginx/app.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - "80:80"
    container_name: m-nginx
    depends_on:
      - php
